Portfolio: details popup window
basitali111/Portfolio-setup-and-mobile-version-skeleton pull request #12
Opened 2022-06-24 17:20 UTC by basitali111

-adding styles for html
-adding html
-adding linters for error
-adding javascript for dynamics

2022-06-24 19:15 UTC, basitali111 commented
sir i want to mention that my coding parthner has commited but due to issue on this branch i delete it and make this new branch but forgot to has its commit

2022-06-24 19:34 UTC, omarsalem7 requested changes
Hi @basitali111 😊, 

Good job so far! 👏
You have done well reaching this point of the milestone, but there are some issues that you still need to work on to go to the next project but you are almost there! 

![you-are-near](https://media.giphy.com/media/SSR17K6yZWvGCYrfUh/giphy.gif)

## Highlights
- Descriptive pull request ✔️
- No linter errors ✔️
- Descriptive commit messages ✔️

## Required Changes ♻️
_Check the comments under the review._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-24 19:34 UTC, omarsalem7 commented on style.css
> +  }
- [ ] Kindly make sure to make your all model appear in the screen or you can make it scrollable by specify `overflow-y:scroll` and give it max-height to be scroll and can see all of it, as in you design the bottom of the model  is hidden.  
> your design
![image](https://user-images.githubusercontent.com/53402600/175653237-57a38cc9-cfad-401e-891f-f5915a03c70d.png)

2022-06-24 20:21 UTC, Ismailco requested changes
### Hi @basitali111,

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights

✔️  No linter errors
✔️ Used Github Flow
✔️ Work documented professionally

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-24 20:21 UTC, Ismailco commented on style.css
> +.workcard {
- [ ] As the previous reviewer mentioned, kindly make the popup appear fully on the screen. for now, the popup is not showing right and can't be scrollable, this will improve the UX

![Screenshot_20220624_211307](https://user-images.githubusercontent.com/25227022/175661115-b2e99cb1-3254-42d6-847a-479c6b33f93a.png)

2022-06-24 20:21 UTC, Ismailco commented on main.js
> +// const works=document.querySelector('.works');
- [ ] [OPTIONAL] For clean code, kindly consider removing all unused code instead of commenting it

2022-06-24 20:21 UTC, Ismailco commented on style.css
> +.workcard {
- [ ] [OPTIONAL] You should implement the above requirements in all repositories in your pair-programming group, kindly consider using peer-programming for the changes or/and don't forget this requirement next time

2022-06-25 01:15 UTC, cwaku approved these changes
Hi @basitali111 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
 - [x] Good job overall following the template design 💯 
 - [x] Correct GitHub Flow 👍🏾 
 - [x] Good commit history 🥇 
 - [x] Good PR title/description 💯 
 - [x] All linters passed 🥇 
 
![](https://media.giphy.com/media/3o6nUX9DoseLZ7JoPu/giphy.gif)

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-25 01:15 UTC, cwaku commented on style.css
> +  }
[ OPTIONAL ]
 - [ ] On a wider screen size the text in the popup card goes a little onto the image. Kindly fix that to have your project look as it is supposed to on all screen sizes.

![image](https://user-images.githubusercontent.com/29071984/175752610-686d7f25-192c-4ce0-8954-b79b2b1a39bd.png)

2022-06-25 14:19 UTC, merged