Portfolio: desktop version
basitali111/Portfolio-setup-and-mobile-version-skeleton pull request #5
Opened 2022-06-10 15:31 UTC by basitali111

Making porfolio by following things:
-Add html file
-Add Css for styling
-Add linters for error checking

2022-06-10 16:16 UTC, ishimwezachee requested changes
Hi @basitali111 , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
![](https://camo.githubusercontent.com/6ac905aa3a075ef45de55758c20c6e6efb1dfdbbb0d9fd03d4718d26c5c96cde/68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f4a713832345239334a734c775a436169534c2f67697068792e676966)

### To highlight 💯 
- Good commit message ✔️ 
- No Linter errors ✔️ 
- Follow Github flow ✔️ 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me on @Ishimwe Zachee  in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
(Not automatically expanded because 3 MB is too large. You can [expand it anyway](https://camo.githubusercontent.com/6ac905aa3a075ef45de55758c20c6e6efb1dfdbbb0d9fd03d4718d26c5c96cde/68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f4a713832345239334a734c775a436169534c2f67697068792e676966) or [open it in a new window](https://camo.githubusercontent.com/6ac905aa3a075ef45de55758c20c6e6efb1dfdbbb0d9fd03d4718d26c5c96cde/68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f4a713832345239334a734c775a436169534c2f67697068792e676966).)

2022-06-10 16:16 UTC, ishimwezachee commented on index.html
> +      </div>
- [ ]  The content of your cards should fit very well in your card as provided in the Figma design.  The size of your cards are very huge, just minimize it and fills its content with the provided data. 

Your design | Figma design
--- | ---
![image](https://user-images.githubusercontent.com/43877689/173106153-1e4f1be8-8def-4905-8b9c-e60869512a2d.png)  | ![image](https://user-images.githubusercontent.com/43877689/173106293-4f91d48b-03c2-4f65-a086-49d75e1924c3.png)

2022-06-10 16:16 UTC, ishimwezachee commented on index.html
> +                ><img src="images/Group.png" alt="linkedprofilelink"
- [ ]  You should have a responsive website for both mobile and desktop. but seemed that you didn't consider this part, to make it responsive to your desktop device. 
![image](https://user-images.githubusercontent.com/43877689/173108026-79958169-6e27-4a3f-b288-db2a9f9c17aa.png)

2022-06-11 20:40 UTC, Ginohmk requested changes
Hi @basitali111  

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![keep-trying-youre-almost-there](https://user-images.githubusercontent.com/67087664/169483884-c624db70-793d-42be-8ebe-afef6a1cd5c3.gif)

 ## Highlights
- No linter errors :+1: 
- USed Github workflow :+1: 

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-11 20:40 UTC, Ginohmk commented on index.html
> +            id="message"
- [Optional] Please remove the excess white space on the right side of the `contact section` of your design.

##### Your design 
![Screenshot from 2022-06-11 21-27-13](https://user-images.githubusercontent.com/58771507/173203837-b4e5edcf-8cff-43b0-941e-b2d869a9af8b.png)

##### Figma Design
![Screenshot from 2022-06-11 21-28-08](https://user-images.githubusercontent.com/58771507/173203857-36c85cda-f637-4777-8f6e-4f3843afe61b.png)

2022-06-11 20:40 UTC, Ginohmk commented on index.html
> +          <input
- Please as the previous reviewer requested, the extra spaces on the desktop view on the right side should be removed so as to make your design look good and similar to the Figma design. 

##### Your design
![Screenshot from 2022-06-11 21-32-38](https://user-images.githubusercontent.com/58771507/173203979-9cbaa237-3eea-47ca-8cdc-edda5f7ccaa6.png)

##### Figna design
![Screenshot from 2022-06-11 21-36-37](https://user-images.githubusercontent.com/58771507/173204117-301a2ea2-51e1-45fb-b157-ab3e99f1d3fd.png)

- Also please remove all extra spaces from the `contact section`, `header section`, and the `about section`., so your design looks like that of the Figma design on desktop view

2022-06-11 22:38 UTC, bimbolabuari approved these changes
Hi @basitali111, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-11 22:44 UTC, merged